on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1" # every Monday at 1am UTC
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - run: nix flake update
      - run: nix flake check --show-trace
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): update flake.lock"
          file_pattern: "flake.lock"
